# Generated by Django 6.0.4 on 2026-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_daily',
            field=models.BooleanField(default=True),
        ),
    ]
